[project]
name = "teleport-docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-chroma>=0.2.4",
    "langchain-huggingface>=0.3.0",
    "sentence-transformers>=5.0.0",
    "mcp>=1.9.4"
]
